time_series_path = "C:\\Users\\brigatto\\Desktop\\ResultsRepository\\NIE.csv"
num_steps_ahead = 24
num_scenarios = 2000
num_windows = 152
fixed_forecast_window_size = false
model_executable_path = "C:\\Users\\brigatto\\Desktop\\ResultsRepository\\model_SARIMA_Log\\SARIMA.bat"
model_name = "SARIMA_Log"
plot_all_scenarios_windows = true